# squidtaild config file

# URL where squidtaild will reference it's files
url			http://some.somecomputer.somewhere/squidtaild
# Note the LACK of a trailing slash...

# File where violations are logged
htmldir		/my/directory/for/squidtaild/
# Note the trailing slash...

# Squid log file
squidlog		/var/log/squid/access.log

# Enable Incremental mode (yes/no)
incremental	yes	

# Truncate URL's (yes/no)
truncate_url yes

# Size of truncated url (characters)
url_length 50

# Status page refresh interval
# (in seconds)
refresh 60

# Lookup hostnames (yes/no)
dnslookups yes


#####################################################
#		MailReporting								#
#		Works only if sendmail is installed!!!!		#
#####################################################

# Enable mail reporting (yes/no)
mailreport 		yes	

# Mailstyle ("text" = plain asci, "html" = HTML style) 
mailstyle		html

# Sendmail Program
sendmail		/usr/sbin/sendmail

# Who should receive the reports
mailrecipient	somebody@somewhere.com	

#####################################################
#		Filter File Locations						#
#####################################################

# Possible Filter file
possible			/etc/squidtaild/filters/possible

# Probably Filter file
probable			/etc/squidtaild/filters/probable

# Definite Filter file
definite			/etc/squidtaild/filters/definite

# Excludes Filter file
excludes			/etc/squidtaild/filters/excludes

#####################################################
#		WinPopUps									#
# Works only if samba is installed					#
# and configured correctly!!!!						#
#####################################################

# Enable winpopups (yes/no)
winpopups		no	

# smbclient program
smbclient		/usr/bin/smbclient

# Send winpopups to users (yes/no)
winpopup_users	no	

# Users winpopup message
user_msg		You have violated our policy!

# Send winpopups to admin (yes/no)
winpopup_admin	no	

# Admin's winpopup message
admin_msg		A policy violation has just occurred!	

# Admin user's netbios name
admin_computer  admin_machine	
