iptables -I INPUT -p tcp -s 10.10.0.102/32 -d 10.10.0.90/32 -i eth1 -j DROP -m comment --comment ' "bloquear maquina de Diego" '
iptables -I INPUT -p icmp -s 10.10.0.102 -i eth1 -j DROP -m state --state NEW,ESTABLISHED,INVALID,RELATED -m comment --comment ' PING DE DIEGO '
