http_port 3128 
cache_dir ufs /var/spool/squid 100 16 256 
#offline_mode off
#icp_port 3130


err_html_text No estas autorizado


hierarchy_stoplist cgi-bin ?
acl QUERY urlpath_regex cgi-bin \?
cache deny QUERY
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern .               0       20%     4320
acl CONNECT method CONNECT

acl all src 0.0.0.0/0.0.0.0
acl localhost src 127.0.0.1/255.255.255.255

http_access allow all
