ip route del 0.0.0.0/0
ip route add 0.0.0.0/0 equalize scope global \
 nexthop via 10.10.0.254 dev eth1  weight 1 onlink \
 nexthop via 10.10.0.252 dev eth1  weight 1 onlink \
 nexthop via 10.10.0.253 dev eth1  weight 1 onlink 
ip route flush cache
