#{ENABLED} ifconfig eth2:234 0
#{ENABLED} ifconfig eth2:82 0
#{ENABLED} ifconfig eth2:215 0
ifconfig eth1:125 0
ifconfig eth1:125 0
ifconfig eth1:150 0
#{ENABLED} ifconfig eth0:189 0 
#{ENABLED} ifconfig eth1:189 0 
#{ENABLED} ifconfig eth1:116 0 
