# Script de inicio de Servicios y modulos del appliance JACK2




sh /root/jack2-interfaces/net-address.sh
sh /root/jack2-routes/net-routes.sh
sh /root/jack2-mpathroute/mpathroutes.sh
sh /root/jack2-dhcp-server/dhcp-server.sh
sh /root/jack2-dhcp-client/dhcp-client.sh
sh /root/jack2-dnsclient/dnsclient.sh
sh /root/jack2-pppoe-client/pppoe-client.sh
sh /root/jack2-pptp-client/pptp-client.sh
sh /root/jack2-pptp-server/pptp-server.sh
sh /root/jack2-proxy/proxy.sh
sh /root/jack2-vrrp/vrrp.sh
sh /opt/jack2/ipsec.prescript.sh
sh /root/jack2-ipsec/ipsec.sh
sh /root/jack2-firewall/fw.sh


