#
# Simple racoon.conf

path pre_shared_key "/etc/racoon/psk.txt";
log debug2;



remote 10.10.0.98 {
       exchange_mode main;
#       proposal_check obey;
       proposal {
                 encryption_algorithm 3des;
                 hash_algorithm md5;
                 authentication_method pre_shared_key;
                 dh_group modp1024;
                }
                generate_policy off;
#               initial_contact on;
}


sainfo anonymous {
    pfs_group modp1024;
    encryption_algorithm 3des;
    authentication_algorithm hmac_md5;
    compression_algorithm deflate;
}


