# /etc/discover.conf: hardware detection settings

# Default settings:
#
# Enable the PCI, USB, IDE, and SCSI bus scans:
enable pci,usb,ide,scsi
# Enable the PCMCIA scan too:
enable pcmcia
# The ISA bus scan causes problems on some machines, and is slow,
# so we might not want to scan these devices:
enable isa
#disable isa
# The parallel and serial scans cause problems on some machines too:
disable parallel,serial

# Scan for the following types of hardware at boot time:
#boot bridge cdrom disk ethernet ide scsi sound usb video
boot all

# Don't load the i810-tco and i8xx-tco module by default:
skip i810-tco
skip i8xx-tco
