# IP protocols logger - Configuration file
# See ippl.conf(5)

# User used
# ---------
# Specify the user (declared in /etc/passwd) used to run the
# logging threads. The ippl process visible in the process table
# is still running as root! Look in /proc/pid/task to see the threads
# running as Debian-ippl
runas Debian-ippl

# Resolve hostnames?
# ------------------
# Uncomment the line below to enable DNS lookups
#resolve all

# Use ident?
# ----------
# Uncomment the line below to enable IDENT lookups
#ident

# Log end of TCP connections ?
# ----------------------------
# Uncomment the line below to enable logging of closing TCP connections
# See the BUGS file.
logclosing

# Expiration of DNS data
# ----------------------
#expire 3600

# Log in a file
# -------------
# Uncomment this line if you want to log messages into a /var/log/ippl.log
# See ippl.conf(5) for the syntax.
log-in all /var/log/ippl/all.log
log-in udp /var/log/ippl/udp.log

# Protocols logged
# ----------------
run icmp tcp
# Uncomment the line below to log UDP traffic.
# See ippl.conf(5) for recommendations.
run udp

# Resolve tcp/udp port to service name?
# -------------------------------------
 portresolve icmp tcp udp
# Set noportresolve <protocol-list> to log port numbers instead

# Logging format
# ----------------
# If you want to see the destination address, the ports, etc
# Or if you want to log the minimal information.
# See ippl.conf(5) for details.
logformat detailed all

# Filtering of packets logged
# ---------------------------

# Do not log answers to echo requests
ignore icmp type echo_reply

# Log telnet connections using ident and name resolution
log options ident,resolve tcp port telnet

# Do not log UDP from localhost
#ignore udp from localhost

# Do not log DNS queries
#ignore udp port domain
#ignore udp srcport domain

# End of configuration
# Copyright (C) 1998-1999 Hugo Haas - Etienne Bernard
