#/etc/ipsec.conf - Openswan IPsec configuration file
# RCSID $Id: ipsec.conf.in,v 1.15.2.4 2006/07/11 16:17:53 paul Exp $


version	2.0	# conforms to second version of ipsec.conf specification

config setup
	interfaces=%none
	# plutodebug / klipsdebug = "all", "none" or a combation from below:
	nat_traversal=yes
	nhelpers=0



#Disable Opportunistic Encryption
#include /etc/ipsec.d/examples/no_oe.conf
include /opt/jack2/ipsec.DEFAULT.conf

include /opt/jack2/ipsec.*.conf
