[global]                                                
port = 1701                                             
auth file = /etc/l2tp/l2tp-secrets                      
;access control = no                                     



[lns default]                                           
exclusive = yes                                         
ip range = 192.168.254.202-192.168.254.210              
lac = 131.193.50.165                                    
hidden bit = no                                         
local ip = 192.168.254.201                              
length bit = yes                                        
refuse authentication = yes                             
name = l2tpd
ppp debug = yes                                         
pppoptfile = /etc/l2tp/options.l2tp                     

[lac cliente]                                               
lns = 10.10.0.254                                    
;redial = yes
;redial timeout = 5
;autodial = yes 
refuse authentication = yes                             
name = l2tpj                                           
ppp debug = yes                                         
pppoptfile = /etc/l2tp/options.l2tp   
