#!/bin/sh
# Start/stop the FreeRADIUS daemon.

### BEGIN INIT INFO
# Provides:          radiusd
# Required-Start:    $network
# Should-Start:      $time mysql ldap postgresql samba krb5-kdc
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Radius Daemon 
# Description:       Extensible, configurable radius daemon
### END INIT INFO

set -e

. /lib/lsb/init-functions

PROG="freeradius"
PROGRAM="/usr/sbin/freeradius"
PIDFILE="/var/run/freeradius/freeradius.pid"
DESCR="FreeRADIUS daemon"

test -f $PROGRAM || exit 0

# /var/run may be a tmpfs
if [ ! -d /var/run/freeradius ]; then
  mkdir -p /var/run/freeradius
  chown freerad:freerad /var/run/freeradius
fi

ret=0

case "$1" in
        start)
                log_daemon_msg "Starting $DESCR" "$PROG"
                if start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $PROGRAM; then
                  ret=$?
                fi
                log_end_msg $ret
                exit $ret
                ;;
        stop)
                log_daemon_msg "Stopping $DESCR" "$PROG"
                if [ -f "$PIDFILE" ] ; then
                  if start-stop-daemon --stop --retry=TERM/30/KILL/5 --quiet --pidfile $PIDFILE; then
                    ret=$?
                  fi
                  log_end_msg $ret
                else 
                  log_action_cont_msg "$PIDFILE not found"
                  log_end_msg 0
                fi
                ;;
        restart)
                $0 stop
                $0 start
                ;;
        reload | force-reload) 
                log_action_begin_msg "Reloading configuration files for $DESCR"
                if [ -f "$PIDFILE" ] ; then
                  if start-stop-daemon --oknodo --stop --signal 1 --quiet --pidfile $PIDFILE; then
                    ret=$?
                  fi
                  log_action_cont_msg "HUP sent"
                  sleep 2
                  if kill -0 $(cat $PIDFILE) > /dev/null; then
                    ret=$(($ret|$?))
                  fi
                  if [ "$ret" -ne 0 ]; then
                    log_action_cont_msg "$DESCR has died!"
                  fi
                  log_end_msg $ret
                else 
                  log_action_cont_msg "$PIDFILE not found"
                  log_end_msg 0
                fi
                exit $ret
                ;;
        *)
                echo "Usage: $0 start|stop|restart|reload|force-reload"
                exit 1 
                ;;
esac

exit 0
